/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JhWLUNKQVqp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export default function Footer() {
  return (
    <footer className="bg-gray-100 p-6 md:py-12 w-full dark:bg-gray-800">
      <div className="container max-w-7xl flex flex-col items-center gap-4 text-sm md:flex-row md:justify-between">
        <p className="text-gray-500 dark:text-gray-400">© 2024 URL Shortener. All rights reserved.</p>
        <div className="flex gap-4">
          <Link className="hover:underline underline-offset-4" href="#">
            Privacy Policy
          </Link>
          <Link className="hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
        </div>
      </div>
    </footer>
  )
}
