/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/H2uxu17NJSS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Settings() {
  return (
    <div className="max-w-md mx-auto p-6 sm:p-8 lg:p-10 space-y-8">
      <div className="flex items-center gap-4">
        <img
          className="rounded-full"
          height={64}
          src="/placeholder.svg"
          style={{
            aspectRatio: "64/64",
            objectFit: "cover",
          }}
          width={64}
        />
        <div>
          <h1 className="text-xl font-semibold" />
          <div className="text-sm text-gray-500 dark:text-gray-400">@</div>
        </div>
      </div>
      <div className="space-y-4">
        <div>
          <h2 className="text-lg font-semibold">Bio</h2>
          <p className="text-gray-500 dark:text-gray-400" />
        </div>
        <div>
          <h2 className="text-lg font-semibold">Edit Profile</h2>
          <form className="space-y-4">
            <div>
              <Label htmlFor="name">Name</Label>
              <Input id="name" />
            </div>
            <div>
              <Label htmlFor="username">Username</Label>
              <Input id="username" />
            </div>
            <div>
              <Label htmlFor="bio">Bio</Label>
              <Textarea className="min-h-[100px]" id="bio" />
            </div>
            <div>
              <Label htmlFor="image">Profile Image</Label>
              <Input id="image" type="file" />
            </div>
            <Button className="ml-auto">Save</Button>
          </form>
        </div>
      </div>
    </div>
  )
}
