/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YRlyllkepn4
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Chivo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";

export function Website() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-4 px-6 md:px-8">
        <div className="container mx-auto flex items-center justify-between">
          <Link className="text-xl font-bold" href="#">
            URL Shortener
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:underline" href="#">
              Shorten URL
            </Link>
            <Link className="hover:underline" href="#">
              History
            </Link>
          </nav>
          <Button className="md:hidden" variant="outline">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1 py-12 px-6 md:px-8">
        <div className="container mx-auto max-w-xl space-y-8">
          <div>
            <h1 className="text-3xl font-bold mb-2">Shorten Your URL</h1>
            <p className="text-gray-500">
              Enter a long URL and we'll generate a short, easy-to-share link.
            </p>
          </div>
          <form className="space-y-4">
            <div>
              <Label htmlFor="url">Long URL</Label>
              <Input
                id="url"
                placeholder="https://example.com/very-long-url"
                required
                type="url"
              />
            </div>
            <Button className="w-full" type="submit">
              Shorten URL
            </Button>
          </form>
          <div className="bg-gray-100 dark:bg-gray-800 p-6 rounded-lg">
            <h2 className="text-lg font-bold mb-2">Your Shortened URL</h2>
            <div className="flex items-center justify-between">
              <p className="text-gray-900 dark:text-gray-100 font-medium">
                https://short.com/abc123
              </p>
              <Button size="sm" variant="outline">
                Copy
              </Button>
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold mb-4">History</h2>
            <div className="space-y-4">
              <div className="bg-gray-100 dark:bg-gray-800 p-4 rounded-lg flex items-center justify-between">
                <div>
                  <p className="text-gray-900 dark:text-gray-100 font-medium">
                    https://example.com/very-long-url
                  </p>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">
                    https://short.com/abc123
                  </p>
                </div>
                <Button size="sm" variant="outline">
                  Copy
                </Button>
              </div>
              <div className="bg-gray-100 dark:bg-gray-800 p-4 rounded-lg flex items-center justify-between">
                <div>
                  <p className="text-gray-900 dark:text-gray-100 font-medium">
                    https://another-long-url.com/example
                  </p>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">
                    https://short.com/def456
                  </p>
                </div>
                <Button size="sm" variant="outline">
                  Copy
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-gray-900 text-white py-4 px-6 md:px-8">
        <div className="container mx-auto text-center text-sm">
          © 2024 URL Shortener. All rights reserved.
        </div>
      </footer>
    </div>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}
